language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
  - "iojs-v1"
  - "iojs-v2"
matrix:
  allow_failures:
    - node_js: 5
sudo: false
cache:
  apt: true
  directories:
  - node_modules/
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-seanjs' ]; then cd .. && eval "mv $currentfolder generator-seanjs" && cd generator-seanjs; fi
